/**
 * ════════════════════════════════════════════════════════════════
 *  AI-Generated Code Detection System
 * ════════════════════════════════════════════════════════════════
 *
 *  Multi-layer analysis to detect whether submitted code was
 *  likely written by a human or generated by AI (ChatGPT, Gemini, etc.)
 *
 *  Layers:
 *    1. Heuristic Analysis  – pattern-based local checks
 *    2. Behavioral Analysis – typing/paste/focus data from integrity logs
 *    3. Gemini Analysis     – LLM-powered content analysis
 *
 *  Output: AI probability score (0–100), detailed breakdown, flags
 */

import axios from 'axios';

const GEMINI_API_KEY = import.meta.env.VITE_GEMINI_API_KEY;
const GEMINI_URL = 'https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent';

// ───────────────────────────────────────────────────────────────
//  1. Heuristic Analysis (local, instant)
// ───────────────────────────────────────────────────────────────

function heuristicAnalysis(code, language) {
  const signals = [];
  let score = 0;
  const lines = code.split('\n');
  const nonEmptyLines = lines.filter(l => l.trim().length > 0);

  // ── Comment patterns ──
  const commentLines = lines.filter(l => {
    const t = l.trim();
    return t.startsWith('//') || t.startsWith('#') || t.startsWith('/*') || t.startsWith('*');
  });
  const commentRatio = nonEmptyLines.length > 0 ? commentLines.length / nonEmptyLines.length : 0;

  // AI tends to over-comment (30%+ comment ratio is suspicious)
  if (commentRatio > 0.35) {
    score += 15;
    signals.push({ type: 'high_comment_ratio', detail: `${(commentRatio * 100).toFixed(0)}% of lines are comments`, weight: 15 });
  }

  // AI often writes "Step X:" or "Case X:" style comments
  const stepComments = commentLines.filter(l => /step\s*\d|case\s*\d|approach|explanation|note:/i.test(l));
  if (stepComments.length >= 3) {
    score += 10;
    signals.push({ type: 'structured_comments', detail: `${stepComments.length} structured/tutorial-style comments`, weight: 10 });
  }

  // ── Consistent formatting ──
  // AI code tends to have perfectly uniform indentation
  const indents = nonEmptyLines.map(l => l.match(/^(\s*)/)[1].length).filter(n => n > 0);
  if (indents.length > 5) {
    const indentSet = new Set(indents);
    const allMultiplesOf4 = [...indentSet].every(n => n % 4 === 0);
    const allMultiplesOf2 = [...indentSet].every(n => n % 2 === 0);
    if (allMultiplesOf4 && indentSet.size <= 4) {
      score += 5;
      signals.push({ type: 'perfect_indentation', detail: 'Perfectly uniform 4-space indentation throughout', weight: 5 });
    } else if (allMultiplesOf2 && indentSet.size <= 5) {
      score += 3;
      signals.push({ type: 'uniform_indentation', detail: 'Very consistent 2-space indentation', weight: 3 });
    }
  }

  // ── Verbose variable names ──
  // AI tends to use descriptive names like "currentElement", "leftSubtree"
  const identifiers = code.match(/\b[a-z][a-zA-Z]{8,}\b/g) || [];
  const camelCaseVerbose = identifiers.filter(id => /[a-z][A-Z]/.test(id) && id.length > 12);
  if (camelCaseVerbose.length >= 5) {
    score += 8;
    signals.push({ type: 'verbose_naming', detail: `${camelCaseVerbose.length} overly descriptive variable names`, weight: 8 });
  }

  // ── Error handling patterns ──
  // AI almost always adds try-catch / error handling even for simple code
  const tryCatchCount = (code.match(/try\s*{|try:|except|catch\s*\(/g) || []).length;
  if (tryCatchCount >= 3 && nonEmptyLines.length < 80) {
    score += 10;
    signals.push({ type: 'excessive_error_handling', detail: `${tryCatchCount} try-catch blocks in ${nonEmptyLines.length} lines`, weight: 10 });
  }

  // ── Boilerplate/template patterns ──
  const boilerplatePatterns = [
    /def main\(\):/,
    /if __name__\s*==\s*['"]__main__['"]/,
    /public static void main/,
    /int main\(\)/,
  ];
  const boilerplateCount = boilerplatePatterns.filter(p => p.test(code)).length;

  // ── Docstring/JSDoc patterns ──
  const docstringCount = (code.match(/"""/g) || []).length / 2 +
    (code.match(/\/\*\*/g) || []).length;
  if (docstringCount >= 3 && nonEmptyLines.length < 60) {
    score += 8;
    signals.push({ type: 'excessive_docs', detail: `${Math.floor(docstringCount)} docstrings in a short file`, weight: 8 });
  }

  // ── Function-heavy structure ──
  // AI tends to break things into many small functions even when not needed
  const funcDefs = (code.match(/\bdef\s+\w+|function\s+\w+|void\s+\w+\s*\(|int\s+\w+\s*\(|bool\s+\w+\s*\(/g) || []).length;
  if (funcDefs >= 6 && nonEmptyLines.length < 80) {
    score += 8;
    signals.push({ type: 'over_modularized', detail: `${funcDefs} functions in ${nonEmptyLines.length} lines`, weight: 8 });
  }

  // ── "AI signature" phrases ──
  const aiPhrases = [
    'here is', 'as follows', 'implementation', 'the following',
    'time complexity', 'space complexity', 'edge case',
    'helper function', 'utility function', 'driver code',
  ];
  const foundPhrases = aiPhrases.filter(p =>
    code.toLowerCase().includes(p)
  );
  if (foundPhrases.length >= 3) {
    score += 12;
    signals.push({ type: 'ai_vocabulary', detail: `Found AI-typical phrases: ${foundPhrases.join(', ')}`, weight: 12 });
  }

  // ── Completeness for assignment ──
  // If code is suspiciously complete with zero TODOs and perfectly structured
  const hasTodo = /TODO|FIXME|HACK|XXX/i.test(code);
  const hasDebug = /console\.log|print\s*\(.*debug|System\.out\.println.*test/i.test(code);
  if (!hasTodo && !hasDebug && nonEmptyLines.length > 30 && commentRatio > 0.15) {
    score += 5;
    signals.push({ type: 'too_clean', detail: 'No TODOs, no debug prints, perfectly clean code', weight: 5 });
  }

  return {
    score: Math.min(score, 60), // heuristic caps at 60
    signals,
    lineCount: nonEmptyLines.length,
    commentRatio: Math.round(commentRatio * 100),
  };
}

// ───────────────────────────────────────────────────────────────
//  2. Behavioral Analysis (from integrity logs)
// ───────────────────────────────────────────────────────────────

function behavioralAnalysis(integrityReport) {
  if (!integrityReport) return { score: 0, signals: [] };

  const signals = [];
  let score = 0;
  const { summary, flags } = integrityReport;

  // ── Paste activity ──
  if (summary.pasteEventsCount > 3) {
    const add = Math.min(summary.pasteEventsCount * 3, 20);
    score += add;
    signals.push({ type: 'high_paste', detail: `${summary.pasteEventsCount} paste events detected`, weight: add });
  }
  if (summary.suspectedPasteFlags > 0) {
    score += 10;
    signals.push({ type: 'suspected_pastes', detail: `${summary.suspectedPasteFlags} pastes flagged as suspicious`, weight: 10 });
  }

  // ── Focus loss ──
  if (flags.excessiveFocusLoss) {
    score += 8;
    signals.push({ type: 'focus_loss', detail: `${summary.focusLossEvents} focus loss events (copying from another source?)`, weight: 8 });
  }

  // ── AI assistant usage ──
  if (summary.aiUsageCount > 10) {
    const add = Math.min(summary.aiUsageCount, 15);
    score += add;
    signals.push({ type: 'heavy_ai_usage', detail: `Used AI assistant ${summary.aiUsageCount} times`, weight: add });
  }

  // ── Typing patterns ──
  const typing = summary.typingPattern;
  if (typing) {
    // Very few keystrokes relative to code length = likely pasted
    if (typing.sampleSize < 20) {
      score += 12;
      signals.push({ type: 'low_keystrokes', detail: `Only ${typing.sampleSize} keystrokes recorded — likely pasted code`, weight: 12 });
    }

    // Extremely uniform typing (robot-like) is suspicious
    if (typing.stdDeviation < 30 && typing.sampleSize > 30) {
      score += 5;
      signals.push({ type: 'uniform_typing', detail: `Typing std deviation: ${typing.stdDeviation}ms (unusually uniform)`, weight: 5 });
    }
  }

  // ── Tab switches ──
  if (summary.tabSwitchEvents > 15) {
    score += 5;
    signals.push({ type: 'high_tab_switching', detail: `${summary.tabSwitchEvents} tab switches`, weight: 5 });
  }

  // ── Rapid focus switching ──
  if (flags.rapidFocusSwitching) {
    score += 8;
    signals.push({ type: 'rapid_switching', detail: 'Rapid tab switching pattern detected', weight: 8 });
  }

  // ── DevTools ──
  if (flags.devtoolsDetected) {
    score += 5;
    signals.push({ type: 'devtools', detail: 'Browser DevTools were opened', weight: 5 });
  }

  return {
    score: Math.min(score, 40), // behavioral caps at 40
    signals,
  };
}

// ───────────────────────────────────────────────────────────────
//  3. Gemini-Powered Analysis (deep content check)
// ───────────────────────────────────────────────────────────────

async function geminiAnalysis(code, language) {
  if (!GEMINI_API_KEY || GEMINI_API_KEY === 'your-gemini-api-key-here') {
    return { score: 0, signals: [{ type: 'skipped', detail: 'Gemini API key not configured', weight: 0 }], rawResponse: null };
  }

  const prompt = `You are an academic integrity expert analyzing student-submitted code for signs of AI generation.

Analyze this ${language} code and evaluate whether it was likely written by a human student or generated by an AI tool (ChatGPT, GitHub Copilot, Gemini, etc.).

IMPORTANT: Respond ONLY with a JSON object, no markdown, no explanation outside the JSON:
{
  "aiProbability": <number 0-100>,
  "confidence": "<low|medium|high>",
  "reasoning": "<2-3 sentence explanation>",
  "indicators": [
    {"signal": "<indicator name>", "description": "<brief detail>", "weight": "<low|medium|high>"}
  ]
}

Indicators to look for:
- Overly polished comments and documentation for a student assignment
- Perfectly structured code with textbook patterns
- Consistent indentation and formatting throughout
- Use of advanced patterns unexpected for the assignment level
- Typical AI output phrases in comments
- Lack of iterative development signs (no debug code, no commented-out experiments)
- Generic variable naming patterns common in AI output

CODE TO ANALYZE:
\`\`\`${language}
${code.slice(0, 3000)}
\`\`\``;

  try {
    const response = await axios({
      url: GEMINI_URL,
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'X-goog-api-key': GEMINI_API_KEY,
      },
      data: {
        contents: [{ parts: [{ text: prompt }] }],
        generationConfig: {
          temperature: 0.3,
          maxOutputTokens: 1024,
        },
      },
    });

    const text = response.data.candidates[0].content.parts[0].text;

    // Extract JSON from response (handle markdown wrapping)
    const jsonMatch = text.match(/\{[\s\S]*\}/);
    if (!jsonMatch) {
      return { score: 0, signals: [{ type: 'parse_error', detail: 'Could not parse Gemini response', weight: 0 }], rawResponse: text };
    }

    const result = JSON.parse(jsonMatch[0]);

    const signals = (result.indicators || []).map(ind => ({
      type: `gemini_${ind.signal?.replace(/\s+/g, '_').toLowerCase() || 'signal'}`,
      detail: ind.description,
      weight: ind.weight === 'high' ? 10 : ind.weight === 'medium' ? 5 : 2,
    }));

    return {
      score: Math.round(result.aiProbability * 0.4), // scale to 0-40 range
      probability: result.aiProbability,
      confidence: result.confidence,
      reasoning: result.reasoning,
      signals,
      rawResponse: result,
    };
  } catch (err) {
    return {
      score: 0,
      signals: [{ type: 'api_error', detail: `Gemini analysis failed: ${err.message}`, weight: 0 }],
      rawResponse: null,
    };
  }
}

// ───────────────────────────────────────────────────────────────
//  Combined Detection Pipeline
// ───────────────────────────────────────────────────────────────

export async function detectAiGenerated(code, language, integrityReport) {
  const heuristic = heuristicAnalysis(code, language);
  const behavioral = behavioralAnalysis(integrityReport);
  const gemini = await geminiAnalysis(code, language);

  const rawScore = heuristic.score + behavioral.score + gemini.score;
  const totalScore = Math.min(Math.max(rawScore, 0), 100);

  // Determine verdict
  let verdict, riskLevel;
  if (totalScore >= 75) {
    verdict = 'Highly likely AI-generated';
    riskLevel = 'critical';
  } else if (totalScore >= 50) {
    verdict = 'Likely AI-assisted';
    riskLevel = 'high';
  } else if (totalScore >= 25) {
    verdict = 'Possibly AI-assisted';
    riskLevel = 'medium';
  } else {
    verdict = 'Likely human-written';
    riskLevel = 'low';
  }

  return {
    score: totalScore,
    verdict,
    riskLevel,
    breakdown: {
      heuristic: {
        score: heuristic.score,
        maxScore: 60,
        signals: heuristic.signals,
        meta: { lineCount: heuristic.lineCount, commentRatio: heuristic.commentRatio },
      },
      behavioral: {
        score: behavioral.score,
        maxScore: 40,
        signals: behavioral.signals,
      },
      gemini: {
        score: gemini.score,
        maxScore: 40,
        probability: gemini.probability,
        confidence: gemini.confidence,
        reasoning: gemini.reasoning,
        signals: gemini.signals,
      },
    },
    allSignals: [...heuristic.signals, ...behavioral.signals, ...gemini.signals],
    timestamp: new Date().toISOString(),
  };
}

export default detectAiGenerated;
